// Generated by CoffeeScript 1.6.3
var HapiSSE;

HapiSSE = (function() {
  function HapiSSE() {
    this._users = {};
  }

  HapiSSE.prototype.isOnline = function(user) {
    return this._users[user] != null;
  };

  HapiSSE.prototype.sendMsgTo = function(user, msg) {
    var data;
    if (!this.isOnline(user)) {
      throw new Error('user is offline');
    }
    data = 'data: ' + msg + "\n\n";
    return this._users[user].write(data);
  };

  HapiSSE.prototype._addUser = function(user, stream) {
    return this._users[user] = stream;
  };

  HapiSSE.prototype._delUser = function(user) {
    this._users[user].end();
    return delete this._users[user];
  };

  return HapiSSE;

})();

module.exports = HapiSSE;
